version: '3.4'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: phpapacheoci8
    container_name: ampweb
    links:
      - db
    ports:
      - "8001:80"
    volumes:
      - ./www:/var/www/html      
  db:
    image: mysql:5.7
    container_name: ampdb
    ports:
      - "9906:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    volumes:
      - ./data:/var/lib/mysql
  admin:
    image: phpmyadmin/phpmyadmin
    container_name: ampadmin
    depends_on:
      - db
    environment:
      - PMA_HOST = db
    ports:
      - "9001:80"
